# Generated by Django 5.1.6 on 2025-03-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrequest',
            name='vendor_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycrequest',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
