# Generated by Django 5.1.6 on 2025-03-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycrequest_vendor_data_alter_kycrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycrequest',
            name='vendor_data',
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='verification_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
