# Generated by Django 5.1.6 on 2025-03-10 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_remove_kycrequest_verification_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('document_id', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='KYCRequest',
        ),
        migrations.AddField(
            model_name='sessiondetails',
            name='personal_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_details', to='kyc.userdetails'),
        ),
    ]
