# Generated by Django 5.1.6 on 2025-03-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_sessiondetails_userdetails_delete_kycrequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='document_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
